name: saltstack-squid-formula
source: https://github.com/bechtoldt/saltstack-squid-formula
summary: SaltStack Formula to set up and configure Squid, a caching proxy for the Web
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
